/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppVisitsRouteImport } from './routes/_authenticated/app/visits'
import { Route as AuthenticatedAppVisitFormSettingsRouteImport } from './routes/_authenticated/app/visit-form-settings'
import { Route as AuthenticatedAppVisitAuditRouteImport } from './routes/_authenticated/app/visit-audit'
import { Route as AuthenticatedAppVehiclesRouteImport } from './routes/_authenticated/app/vehicles'
import { Route as AuthenticatedAppTradeInvoicesRouteImport } from './routes/_authenticated/app/trade-invoices'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/app/tasks'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppSensorsRouteImport } from './routes/_authenticated/app/sensors'
import { Route as AuthenticatedAppSalesOrdersRouteImport } from './routes/_authenticated/app/sales-orders'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app/reports'
import { Route as AuthenticatedAppPortalRouteImport } from './routes/_authenticated/app/portal'
import { Route as AuthenticatedAppPlansRouteImport } from './routes/_authenticated/app/plans'
import { Route as AuthenticatedAppPharmaciesRouteImport } from './routes/_authenticated/app/pharmacies'
import { Route as AuthenticatedAppPaymentsRouteImport } from './routes/_authenticated/app/payments'
import { Route as AuthenticatedAppPatientsRouteImport } from './routes/_authenticated/app/patients'
import { Route as AuthenticatedAppNutritionistsRouteImport } from './routes/_authenticated/app/nutritionists'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app/notifications'
import { Route as AuthenticatedAppLifecycleRouteImport } from './routes/_authenticated/app/lifecycle'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app/leads'
import { Route as AuthenticatedAppLabsRouteImport } from './routes/_authenticated/app/labs'
import { Route as AuthenticatedAppInventoryRouteImport } from './routes/_authenticated/app/inventory'
import { Route as AuthenticatedAppHospitalsRouteImport } from './routes/_authenticated/app/hospitals'
import { Route as AuthenticatedAppDoctorsRouteImport } from './routes/_authenticated/app/doctors'
import { Route as AuthenticatedAppDistributionReportsRouteImport } from './routes/_authenticated/app/distribution-reports'
import { Route as AuthenticatedAppDistributionDashboardRouteImport } from './routes/_authenticated/app/distribution-dashboard'
import { Route as AuthenticatedAppDistributionCatalogRouteImport } from './routes/_authenticated/app/distribution-catalog'
import { Route as AuthenticatedAppDeliveriesRouteImport } from './routes/_authenticated/app/deliveries'
import { Route as AuthenticatedAppDealersRouteImport } from './routes/_authenticated/app/dealers'
import { Route as AuthenticatedAppDealerPaymentsRouteImport } from './routes/_authenticated/app/dealer-payments'
import { Route as AuthenticatedAppDealerLedgerRouteImport } from './routes/_authenticated/app/dealer-ledger'
import { Route as AuthenticatedAppCommissionsRouteImport } from './routes/_authenticated/app/commissions'
import { Route as AuthenticatedAppClinicalRouteImport } from './routes/_authenticated/app/clinical'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app/audit'
import { Route as AuthenticatedAppAppointmentsRouteImport } from './routes/_authenticated/app/appointments'
import { Route as AuthenticatedAppAccessRequestsRouteImport } from './routes/_authenticated/app/access-requests'
import { Route as ApiPublicHooksDispatchNotificationsRouteImport } from './routes/api/public/hooks/dispatch-notifications'
import { Route as ApiPublicHooksDealerStatementRouteImport } from './routes/api/public/hooks/dealer-statement'
import { Route as ApiPublicHooksDealerDunningRouteImport } from './routes/api/public/hooks/dealer-dunning'
import { Route as ApiPublicHooksBackupSnapshotRouteImport } from './routes/api/public/hooks/backup-snapshot'
import { Route as AuthenticatedAppPatientsPatientIdRouteImport } from './routes/_authenticated/app/patients.$patientId'
import { Route as AuthenticatedAppTradeInvoicesIdPrintRouteImport } from './routes/_authenticated/app/trade-invoices.$id.print'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVisitsRoute = AuthenticatedAppVisitsRouteImport.update({
  id: '/app/visits',
  path: '/app/visits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVisitFormSettingsRoute =
  AuthenticatedAppVisitFormSettingsRouteImport.update({
    id: '/app/visit-form-settings',
    path: '/app/visit-form-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVisitAuditRoute =
  AuthenticatedAppVisitAuditRouteImport.update({
    id: '/app/visit-audit',
    path: '/app/visit-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVehiclesRoute =
  AuthenticatedAppVehiclesRouteImport.update({
    id: '/app/vehicles',
    path: '/app/vehicles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppTradeInvoicesRoute =
  AuthenticatedAppTradeInvoicesRouteImport.update({
    id: '/app/trade-invoices',
    path: '/app/trade-invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/app/tasks',
  path: '/app/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSensorsRoute = AuthenticatedAppSensorsRouteImport.update({
  id: '/app/sensors',
  path: '/app/sensors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSalesOrdersRoute =
  AuthenticatedAppSalesOrdersRouteImport.update({
    id: '/app/sales-orders',
    path: '/app/sales-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/app/reports',
  path: '/app/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPortalRoute = AuthenticatedAppPortalRouteImport.update({
  id: '/app/portal',
  path: '/app/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPlansRoute = AuthenticatedAppPlansRouteImport.update({
  id: '/app/plans',
  path: '/app/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPharmaciesRoute =
  AuthenticatedAppPharmaciesRouteImport.update({
    id: '/app/pharmacies',
    path: '/app/pharmacies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPaymentsRoute =
  AuthenticatedAppPaymentsRouteImport.update({
    id: '/app/payments',
    path: '/app/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPatientsRoute =
  AuthenticatedAppPatientsRouteImport.update({
    id: '/app/patients',
    path: '/app/patients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppNutritionistsRoute =
  AuthenticatedAppNutritionistsRouteImport.update({
    id: '/app/nutritionists',
    path: '/app/nutritionists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/app/notifications',
    path: '/app/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLifecycleRoute =
  AuthenticatedAppLifecycleRouteImport.update({
    id: '/app/lifecycle',
    path: '/app/lifecycle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/app/leads',
  path: '/app/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppLabsRoute = AuthenticatedAppLabsRouteImport.update({
  id: '/app/labs',
  path: '/app/labs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppInventoryRoute =
  AuthenticatedAppInventoryRouteImport.update({
    id: '/app/inventory',
    path: '/app/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppHospitalsRoute =
  AuthenticatedAppHospitalsRouteImport.update({
    id: '/app/hospitals',
    path: '/app/hospitals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDoctorsRoute = AuthenticatedAppDoctorsRouteImport.update({
  id: '/app/doctors',
  path: '/app/doctors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDistributionReportsRoute =
  AuthenticatedAppDistributionReportsRouteImport.update({
    id: '/app/distribution-reports',
    path: '/app/distribution-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDistributionDashboardRoute =
  AuthenticatedAppDistributionDashboardRouteImport.update({
    id: '/app/distribution-dashboard',
    path: '/app/distribution-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDistributionCatalogRoute =
  AuthenticatedAppDistributionCatalogRouteImport.update({
    id: '/app/distribution-catalog',
    path: '/app/distribution-catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDeliveriesRoute =
  AuthenticatedAppDeliveriesRouteImport.update({
    id: '/app/deliveries',
    path: '/app/deliveries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDealersRoute = AuthenticatedAppDealersRouteImport.update({
  id: '/app/dealers',
  path: '/app/dealers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDealerPaymentsRoute =
  AuthenticatedAppDealerPaymentsRouteImport.update({
    id: '/app/dealer-payments',
    path: '/app/dealer-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDealerLedgerRoute =
  AuthenticatedAppDealerLedgerRouteImport.update({
    id: '/app/dealer-ledger',
    path: '/app/dealer-ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCommissionsRoute =
  AuthenticatedAppCommissionsRouteImport.update({
    id: '/app/commissions',
    path: '/app/commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppClinicalRoute =
  AuthenticatedAppClinicalRouteImport.update({
    id: '/app/clinical',
    path: '/app/clinical',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/app/audit',
  path: '/app/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAppointmentsRoute =
  AuthenticatedAppAppointmentsRouteImport.update({
    id: '/app/appointments',
    path: '/app/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAccessRequestsRoute =
  AuthenticatedAppAccessRequestsRouteImport.update({
    id: '/app/access-requests',
    path: '/app/access-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksDispatchNotificationsRoute =
  ApiPublicHooksDispatchNotificationsRouteImport.update({
    id: '/api/public/hooks/dispatch-notifications',
    path: '/api/public/hooks/dispatch-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDealerStatementRoute =
  ApiPublicHooksDealerStatementRouteImport.update({
    id: '/api/public/hooks/dealer-statement',
    path: '/api/public/hooks/dealer-statement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDealerDunningRoute =
  ApiPublicHooksDealerDunningRouteImport.update({
    id: '/api/public/hooks/dealer-dunning',
    path: '/api/public/hooks/dealer-dunning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackupSnapshotRoute =
  ApiPublicHooksBackupSnapshotRouteImport.update({
    id: '/api/public/hooks/backup-snapshot',
    path: '/api/public/hooks/backup-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppPatientsPatientIdRoute =
  AuthenticatedAppPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedAppPatientsRoute,
  } as any)
const AuthenticatedAppTradeInvoicesIdPrintRoute =
  AuthenticatedAppTradeInvoicesIdPrintRouteImport.update({
    id: '/$id/print',
    path: '/$id/print',
    getParentRoute: () => AuthenticatedAppTradeInvoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/app/access-requests': typeof AuthenticatedAppAccessRequestsRoute
  '/app/appointments': typeof AuthenticatedAppAppointmentsRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/clinical': typeof AuthenticatedAppClinicalRoute
  '/app/commissions': typeof AuthenticatedAppCommissionsRoute
  '/app/dealer-ledger': typeof AuthenticatedAppDealerLedgerRoute
  '/app/dealer-payments': typeof AuthenticatedAppDealerPaymentsRoute
  '/app/dealers': typeof AuthenticatedAppDealersRoute
  '/app/deliveries': typeof AuthenticatedAppDeliveriesRoute
  '/app/distribution-catalog': typeof AuthenticatedAppDistributionCatalogRoute
  '/app/distribution-dashboard': typeof AuthenticatedAppDistributionDashboardRoute
  '/app/distribution-reports': typeof AuthenticatedAppDistributionReportsRoute
  '/app/doctors': typeof AuthenticatedAppDoctorsRoute
  '/app/hospitals': typeof AuthenticatedAppHospitalsRoute
  '/app/inventory': typeof AuthenticatedAppInventoryRoute
  '/app/labs': typeof AuthenticatedAppLabsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/lifecycle': typeof AuthenticatedAppLifecycleRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/nutritionists': typeof AuthenticatedAppNutritionistsRoute
  '/app/patients': typeof AuthenticatedAppPatientsRouteWithChildren
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/pharmacies': typeof AuthenticatedAppPharmaciesRoute
  '/app/plans': typeof AuthenticatedAppPlansRoute
  '/app/portal': typeof AuthenticatedAppPortalRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/sales-orders': typeof AuthenticatedAppSalesOrdersRoute
  '/app/sensors': typeof AuthenticatedAppSensorsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/trade-invoices': typeof AuthenticatedAppTradeInvoicesRouteWithChildren
  '/app/vehicles': typeof AuthenticatedAppVehiclesRoute
  '/app/visit-audit': typeof AuthenticatedAppVisitAuditRoute
  '/app/visit-form-settings': typeof AuthenticatedAppVisitFormSettingsRoute
  '/app/visits': typeof AuthenticatedAppVisitsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/patients/$patientId': typeof AuthenticatedAppPatientsPatientIdRoute
  '/api/public/hooks/backup-snapshot': typeof ApiPublicHooksBackupSnapshotRoute
  '/api/public/hooks/dealer-dunning': typeof ApiPublicHooksDealerDunningRoute
  '/api/public/hooks/dealer-statement': typeof ApiPublicHooksDealerStatementRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/app/trade-invoices/$id/print': typeof AuthenticatedAppTradeInvoicesIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/app/access-requests': typeof AuthenticatedAppAccessRequestsRoute
  '/app/appointments': typeof AuthenticatedAppAppointmentsRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/clinical': typeof AuthenticatedAppClinicalRoute
  '/app/commissions': typeof AuthenticatedAppCommissionsRoute
  '/app/dealer-ledger': typeof AuthenticatedAppDealerLedgerRoute
  '/app/dealer-payments': typeof AuthenticatedAppDealerPaymentsRoute
  '/app/dealers': typeof AuthenticatedAppDealersRoute
  '/app/deliveries': typeof AuthenticatedAppDeliveriesRoute
  '/app/distribution-catalog': typeof AuthenticatedAppDistributionCatalogRoute
  '/app/distribution-dashboard': typeof AuthenticatedAppDistributionDashboardRoute
  '/app/distribution-reports': typeof AuthenticatedAppDistributionReportsRoute
  '/app/doctors': typeof AuthenticatedAppDoctorsRoute
  '/app/hospitals': typeof AuthenticatedAppHospitalsRoute
  '/app/inventory': typeof AuthenticatedAppInventoryRoute
  '/app/labs': typeof AuthenticatedAppLabsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/lifecycle': typeof AuthenticatedAppLifecycleRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/nutritionists': typeof AuthenticatedAppNutritionistsRoute
  '/app/patients': typeof AuthenticatedAppPatientsRouteWithChildren
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/pharmacies': typeof AuthenticatedAppPharmaciesRoute
  '/app/plans': typeof AuthenticatedAppPlansRoute
  '/app/portal': typeof AuthenticatedAppPortalRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/sales-orders': typeof AuthenticatedAppSalesOrdersRoute
  '/app/sensors': typeof AuthenticatedAppSensorsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/trade-invoices': typeof AuthenticatedAppTradeInvoicesRouteWithChildren
  '/app/vehicles': typeof AuthenticatedAppVehiclesRoute
  '/app/visit-audit': typeof AuthenticatedAppVisitAuditRoute
  '/app/visit-form-settings': typeof AuthenticatedAppVisitFormSettingsRoute
  '/app/visits': typeof AuthenticatedAppVisitsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/patients/$patientId': typeof AuthenticatedAppPatientsPatientIdRoute
  '/api/public/hooks/backup-snapshot': typeof ApiPublicHooksBackupSnapshotRoute
  '/api/public/hooks/dealer-dunning': typeof ApiPublicHooksDealerDunningRoute
  '/api/public/hooks/dealer-statement': typeof ApiPublicHooksDealerStatementRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/app/trade-invoices/$id/print': typeof AuthenticatedAppTradeInvoicesIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/app/access-requests': typeof AuthenticatedAppAccessRequestsRoute
  '/_authenticated/app/appointments': typeof AuthenticatedAppAppointmentsRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/clinical': typeof AuthenticatedAppClinicalRoute
  '/_authenticated/app/commissions': typeof AuthenticatedAppCommissionsRoute
  '/_authenticated/app/dealer-ledger': typeof AuthenticatedAppDealerLedgerRoute
  '/_authenticated/app/dealer-payments': typeof AuthenticatedAppDealerPaymentsRoute
  '/_authenticated/app/dealers': typeof AuthenticatedAppDealersRoute
  '/_authenticated/app/deliveries': typeof AuthenticatedAppDeliveriesRoute
  '/_authenticated/app/distribution-catalog': typeof AuthenticatedAppDistributionCatalogRoute
  '/_authenticated/app/distribution-dashboard': typeof AuthenticatedAppDistributionDashboardRoute
  '/_authenticated/app/distribution-reports': typeof AuthenticatedAppDistributionReportsRoute
  '/_authenticated/app/doctors': typeof AuthenticatedAppDoctorsRoute
  '/_authenticated/app/hospitals': typeof AuthenticatedAppHospitalsRoute
  '/_authenticated/app/inventory': typeof AuthenticatedAppInventoryRoute
  '/_authenticated/app/labs': typeof AuthenticatedAppLabsRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRoute
  '/_authenticated/app/lifecycle': typeof AuthenticatedAppLifecycleRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/nutritionists': typeof AuthenticatedAppNutritionistsRoute
  '/_authenticated/app/patients': typeof AuthenticatedAppPatientsRouteWithChildren
  '/_authenticated/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/_authenticated/app/pharmacies': typeof AuthenticatedAppPharmaciesRoute
  '/_authenticated/app/plans': typeof AuthenticatedAppPlansRoute
  '/_authenticated/app/portal': typeof AuthenticatedAppPortalRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/sales-orders': typeof AuthenticatedAppSalesOrdersRoute
  '/_authenticated/app/sensors': typeof AuthenticatedAppSensorsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/app/trade-invoices': typeof AuthenticatedAppTradeInvoicesRouteWithChildren
  '/_authenticated/app/vehicles': typeof AuthenticatedAppVehiclesRoute
  '/_authenticated/app/visit-audit': typeof AuthenticatedAppVisitAuditRoute
  '/_authenticated/app/visit-form-settings': typeof AuthenticatedAppVisitFormSettingsRoute
  '/_authenticated/app/visits': typeof AuthenticatedAppVisitsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/patients/$patientId': typeof AuthenticatedAppPatientsPatientIdRoute
  '/api/public/hooks/backup-snapshot': typeof ApiPublicHooksBackupSnapshotRoute
  '/api/public/hooks/dealer-dunning': typeof ApiPublicHooksDealerDunningRoute
  '/api/public/hooks/dealer-statement': typeof ApiPublicHooksDealerStatementRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/_authenticated/app/trade-invoices/$id/print': typeof AuthenticatedAppTradeInvoicesIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/set-password'
    | '/portal'
    | '/app/access-requests'
    | '/app/appointments'
    | '/app/audit'
    | '/app/clinical'
    | '/app/commissions'
    | '/app/dealer-ledger'
    | '/app/dealer-payments'
    | '/app/dealers'
    | '/app/deliveries'
    | '/app/distribution-catalog'
    | '/app/distribution-dashboard'
    | '/app/distribution-reports'
    | '/app/doctors'
    | '/app/hospitals'
    | '/app/inventory'
    | '/app/labs'
    | '/app/leads'
    | '/app/lifecycle'
    | '/app/notifications'
    | '/app/nutritionists'
    | '/app/patients'
    | '/app/payments'
    | '/app/pharmacies'
    | '/app/plans'
    | '/app/portal'
    | '/app/reports'
    | '/app/sales-orders'
    | '/app/sensors'
    | '/app/settings'
    | '/app/tasks'
    | '/app/trade-invoices'
    | '/app/vehicles'
    | '/app/visit-audit'
    | '/app/visit-form-settings'
    | '/app/visits'
    | '/app/'
    | '/app/patients/$patientId'
    | '/api/public/hooks/backup-snapshot'
    | '/api/public/hooks/dealer-dunning'
    | '/api/public/hooks/dealer-statement'
    | '/api/public/hooks/dispatch-notifications'
    | '/app/trade-invoices/$id/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/set-password'
    | '/portal'
    | '/app/access-requests'
    | '/app/appointments'
    | '/app/audit'
    | '/app/clinical'
    | '/app/commissions'
    | '/app/dealer-ledger'
    | '/app/dealer-payments'
    | '/app/dealers'
    | '/app/deliveries'
    | '/app/distribution-catalog'
    | '/app/distribution-dashboard'
    | '/app/distribution-reports'
    | '/app/doctors'
    | '/app/hospitals'
    | '/app/inventory'
    | '/app/labs'
    | '/app/leads'
    | '/app/lifecycle'
    | '/app/notifications'
    | '/app/nutritionists'
    | '/app/patients'
    | '/app/payments'
    | '/app/pharmacies'
    | '/app/plans'
    | '/app/portal'
    | '/app/reports'
    | '/app/sales-orders'
    | '/app/sensors'
    | '/app/settings'
    | '/app/tasks'
    | '/app/trade-invoices'
    | '/app/vehicles'
    | '/app/visit-audit'
    | '/app/visit-form-settings'
    | '/app/visits'
    | '/app'
    | '/app/patients/$patientId'
    | '/api/public/hooks/backup-snapshot'
    | '/api/public/hooks/dealer-dunning'
    | '/api/public/hooks/dealer-statement'
    | '/api/public/hooks/dispatch-notifications'
    | '/app/trade-invoices/$id/print'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/set-password'
    | '/_authenticated/portal'
    | '/_authenticated/app/access-requests'
    | '/_authenticated/app/appointments'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/clinical'
    | '/_authenticated/app/commissions'
    | '/_authenticated/app/dealer-ledger'
    | '/_authenticated/app/dealer-payments'
    | '/_authenticated/app/dealers'
    | '/_authenticated/app/deliveries'
    | '/_authenticated/app/distribution-catalog'
    | '/_authenticated/app/distribution-dashboard'
    | '/_authenticated/app/distribution-reports'
    | '/_authenticated/app/doctors'
    | '/_authenticated/app/hospitals'
    | '/_authenticated/app/inventory'
    | '/_authenticated/app/labs'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/lifecycle'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/nutritionists'
    | '/_authenticated/app/patients'
    | '/_authenticated/app/payments'
    | '/_authenticated/app/pharmacies'
    | '/_authenticated/app/plans'
    | '/_authenticated/app/portal'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/sales-orders'
    | '/_authenticated/app/sensors'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/tasks'
    | '/_authenticated/app/trade-invoices'
    | '/_authenticated/app/vehicles'
    | '/_authenticated/app/visit-audit'
    | '/_authenticated/app/visit-form-settings'
    | '/_authenticated/app/visits'
    | '/_authenticated/app/'
    | '/_authenticated/app/patients/$patientId'
    | '/api/public/hooks/backup-snapshot'
    | '/api/public/hooks/dealer-dunning'
    | '/api/public/hooks/dealer-statement'
    | '/api/public/hooks/dispatch-notifications'
    | '/_authenticated/app/trade-invoices/$id/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetPasswordRoute: typeof SetPasswordRoute
  ApiPublicHooksBackupSnapshotRoute: typeof ApiPublicHooksBackupSnapshotRoute
  ApiPublicHooksDealerDunningRoute: typeof ApiPublicHooksDealerDunningRoute
  ApiPublicHooksDealerStatementRoute: typeof ApiPublicHooksDealerStatementRoute
  ApiPublicHooksDispatchNotificationsRoute: typeof ApiPublicHooksDispatchNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/visits': {
      id: '/_authenticated/app/visits'
      path: '/app/visits'
      fullPath: '/app/visits'
      preLoaderRoute: typeof AuthenticatedAppVisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/visit-form-settings': {
      id: '/_authenticated/app/visit-form-settings'
      path: '/app/visit-form-settings'
      fullPath: '/app/visit-form-settings'
      preLoaderRoute: typeof AuthenticatedAppVisitFormSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/visit-audit': {
      id: '/_authenticated/app/visit-audit'
      path: '/app/visit-audit'
      fullPath: '/app/visit-audit'
      preLoaderRoute: typeof AuthenticatedAppVisitAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/vehicles': {
      id: '/_authenticated/app/vehicles'
      path: '/app/vehicles'
      fullPath: '/app/vehicles'
      preLoaderRoute: typeof AuthenticatedAppVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/trade-invoices': {
      id: '/_authenticated/app/trade-invoices'
      path: '/app/trade-invoices'
      fullPath: '/app/trade-invoices'
      preLoaderRoute: typeof AuthenticatedAppTradeInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/tasks': {
      id: '/_authenticated/app/tasks'
      path: '/app/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sensors': {
      id: '/_authenticated/app/sensors'
      path: '/app/sensors'
      fullPath: '/app/sensors'
      preLoaderRoute: typeof AuthenticatedAppSensorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sales-orders': {
      id: '/_authenticated/app/sales-orders'
      path: '/app/sales-orders'
      fullPath: '/app/sales-orders'
      preLoaderRoute: typeof AuthenticatedAppSalesOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/portal': {
      id: '/_authenticated/app/portal'
      path: '/app/portal'
      fullPath: '/app/portal'
      preLoaderRoute: typeof AuthenticatedAppPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/plans': {
      id: '/_authenticated/app/plans'
      path: '/app/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AuthenticatedAppPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/pharmacies': {
      id: '/_authenticated/app/pharmacies'
      path: '/app/pharmacies'
      fullPath: '/app/pharmacies'
      preLoaderRoute: typeof AuthenticatedAppPharmaciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/payments': {
      id: '/_authenticated/app/payments'
      path: '/app/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AuthenticatedAppPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/patients': {
      id: '/_authenticated/app/patients'
      path: '/app/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AuthenticatedAppPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/nutritionists': {
      id: '/_authenticated/app/nutritionists'
      path: '/app/nutritionists'
      fullPath: '/app/nutritionists'
      preLoaderRoute: typeof AuthenticatedAppNutritionistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lifecycle': {
      id: '/_authenticated/app/lifecycle'
      path: '/app/lifecycle'
      fullPath: '/app/lifecycle'
      preLoaderRoute: typeof AuthenticatedAppLifecycleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/app/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/labs': {
      id: '/_authenticated/app/labs'
      path: '/app/labs'
      fullPath: '/app/labs'
      preLoaderRoute: typeof AuthenticatedAppLabsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/inventory': {
      id: '/_authenticated/app/inventory'
      path: '/app/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AuthenticatedAppInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/hospitals': {
      id: '/_authenticated/app/hospitals'
      path: '/app/hospitals'
      fullPath: '/app/hospitals'
      preLoaderRoute: typeof AuthenticatedAppHospitalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/doctors': {
      id: '/_authenticated/app/doctors'
      path: '/app/doctors'
      fullPath: '/app/doctors'
      preLoaderRoute: typeof AuthenticatedAppDoctorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/distribution-reports': {
      id: '/_authenticated/app/distribution-reports'
      path: '/app/distribution-reports'
      fullPath: '/app/distribution-reports'
      preLoaderRoute: typeof AuthenticatedAppDistributionReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/distribution-dashboard': {
      id: '/_authenticated/app/distribution-dashboard'
      path: '/app/distribution-dashboard'
      fullPath: '/app/distribution-dashboard'
      preLoaderRoute: typeof AuthenticatedAppDistributionDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/distribution-catalog': {
      id: '/_authenticated/app/distribution-catalog'
      path: '/app/distribution-catalog'
      fullPath: '/app/distribution-catalog'
      preLoaderRoute: typeof AuthenticatedAppDistributionCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/deliveries': {
      id: '/_authenticated/app/deliveries'
      path: '/app/deliveries'
      fullPath: '/app/deliveries'
      preLoaderRoute: typeof AuthenticatedAppDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dealers': {
      id: '/_authenticated/app/dealers'
      path: '/app/dealers'
      fullPath: '/app/dealers'
      preLoaderRoute: typeof AuthenticatedAppDealersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dealer-payments': {
      id: '/_authenticated/app/dealer-payments'
      path: '/app/dealer-payments'
      fullPath: '/app/dealer-payments'
      preLoaderRoute: typeof AuthenticatedAppDealerPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dealer-ledger': {
      id: '/_authenticated/app/dealer-ledger'
      path: '/app/dealer-ledger'
      fullPath: '/app/dealer-ledger'
      preLoaderRoute: typeof AuthenticatedAppDealerLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/commissions': {
      id: '/_authenticated/app/commissions'
      path: '/app/commissions'
      fullPath: '/app/commissions'
      preLoaderRoute: typeof AuthenticatedAppCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/clinical': {
      id: '/_authenticated/app/clinical'
      path: '/app/clinical'
      fullPath: '/app/clinical'
      preLoaderRoute: typeof AuthenticatedAppClinicalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/app/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/appointments': {
      id: '/_authenticated/app/appointments'
      path: '/app/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AuthenticatedAppAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/access-requests': {
      id: '/_authenticated/app/access-requests'
      path: '/app/access-requests'
      fullPath: '/app/access-requests'
      preLoaderRoute: typeof AuthenticatedAppAccessRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/dispatch-notifications': {
      id: '/api/public/hooks/dispatch-notifications'
      path: '/api/public/hooks/dispatch-notifications'
      fullPath: '/api/public/hooks/dispatch-notifications'
      preLoaderRoute: typeof ApiPublicHooksDispatchNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dealer-statement': {
      id: '/api/public/hooks/dealer-statement'
      path: '/api/public/hooks/dealer-statement'
      fullPath: '/api/public/hooks/dealer-statement'
      preLoaderRoute: typeof ApiPublicHooksDealerStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dealer-dunning': {
      id: '/api/public/hooks/dealer-dunning'
      path: '/api/public/hooks/dealer-dunning'
      fullPath: '/api/public/hooks/dealer-dunning'
      preLoaderRoute: typeof ApiPublicHooksDealerDunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backup-snapshot': {
      id: '/api/public/hooks/backup-snapshot'
      path: '/api/public/hooks/backup-snapshot'
      fullPath: '/api/public/hooks/backup-snapshot'
      preLoaderRoute: typeof ApiPublicHooksBackupSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/patients/$patientId': {
      id: '/_authenticated/app/patients/$patientId'
      path: '/$patientId'
      fullPath: '/app/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedAppPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedAppPatientsRoute
    }
    '/_authenticated/app/trade-invoices/$id/print': {
      id: '/_authenticated/app/trade-invoices/$id/print'
      path: '/$id/print'
      fullPath: '/app/trade-invoices/$id/print'
      preLoaderRoute: typeof AuthenticatedAppTradeInvoicesIdPrintRouteImport
      parentRoute: typeof AuthenticatedAppTradeInvoicesRoute
    }
  }
}

interface AuthenticatedAppPatientsRouteChildren {
  AuthenticatedAppPatientsPatientIdRoute: typeof AuthenticatedAppPatientsPatientIdRoute
}

const AuthenticatedAppPatientsRouteChildren: AuthenticatedAppPatientsRouteChildren =
  {
    AuthenticatedAppPatientsPatientIdRoute:
      AuthenticatedAppPatientsPatientIdRoute,
  }

const AuthenticatedAppPatientsRouteWithChildren =
  AuthenticatedAppPatientsRoute._addFileChildren(
    AuthenticatedAppPatientsRouteChildren,
  )

interface AuthenticatedAppTradeInvoicesRouteChildren {
  AuthenticatedAppTradeInvoicesIdPrintRoute: typeof AuthenticatedAppTradeInvoicesIdPrintRoute
}

const AuthenticatedAppTradeInvoicesRouteChildren: AuthenticatedAppTradeInvoicesRouteChildren =
  {
    AuthenticatedAppTradeInvoicesIdPrintRoute:
      AuthenticatedAppTradeInvoicesIdPrintRoute,
  }

const AuthenticatedAppTradeInvoicesRouteWithChildren =
  AuthenticatedAppTradeInvoicesRoute._addFileChildren(
    AuthenticatedAppTradeInvoicesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedAppAccessRequestsRoute: typeof AuthenticatedAppAccessRequestsRoute
  AuthenticatedAppAppointmentsRoute: typeof AuthenticatedAppAppointmentsRoute
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppClinicalRoute: typeof AuthenticatedAppClinicalRoute
  AuthenticatedAppCommissionsRoute: typeof AuthenticatedAppCommissionsRoute
  AuthenticatedAppDealerLedgerRoute: typeof AuthenticatedAppDealerLedgerRoute
  AuthenticatedAppDealerPaymentsRoute: typeof AuthenticatedAppDealerPaymentsRoute
  AuthenticatedAppDealersRoute: typeof AuthenticatedAppDealersRoute
  AuthenticatedAppDeliveriesRoute: typeof AuthenticatedAppDeliveriesRoute
  AuthenticatedAppDistributionCatalogRoute: typeof AuthenticatedAppDistributionCatalogRoute
  AuthenticatedAppDistributionDashboardRoute: typeof AuthenticatedAppDistributionDashboardRoute
  AuthenticatedAppDistributionReportsRoute: typeof AuthenticatedAppDistributionReportsRoute
  AuthenticatedAppDoctorsRoute: typeof AuthenticatedAppDoctorsRoute
  AuthenticatedAppHospitalsRoute: typeof AuthenticatedAppHospitalsRoute
  AuthenticatedAppInventoryRoute: typeof AuthenticatedAppInventoryRoute
  AuthenticatedAppLabsRoute: typeof AuthenticatedAppLabsRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRoute
  AuthenticatedAppLifecycleRoute: typeof AuthenticatedAppLifecycleRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppNutritionistsRoute: typeof AuthenticatedAppNutritionistsRoute
  AuthenticatedAppPatientsRoute: typeof AuthenticatedAppPatientsRouteWithChildren
  AuthenticatedAppPaymentsRoute: typeof AuthenticatedAppPaymentsRoute
  AuthenticatedAppPharmaciesRoute: typeof AuthenticatedAppPharmaciesRoute
  AuthenticatedAppPlansRoute: typeof AuthenticatedAppPlansRoute
  AuthenticatedAppPortalRoute: typeof AuthenticatedAppPortalRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSalesOrdersRoute: typeof AuthenticatedAppSalesOrdersRoute
  AuthenticatedAppSensorsRoute: typeof AuthenticatedAppSensorsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
  AuthenticatedAppTradeInvoicesRoute: typeof AuthenticatedAppTradeInvoicesRouteWithChildren
  AuthenticatedAppVehiclesRoute: typeof AuthenticatedAppVehiclesRoute
  AuthenticatedAppVisitAuditRoute: typeof AuthenticatedAppVisitAuditRoute
  AuthenticatedAppVisitFormSettingsRoute: typeof AuthenticatedAppVisitFormSettingsRoute
  AuthenticatedAppVisitsRoute: typeof AuthenticatedAppVisitsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedAppAccessRequestsRoute: AuthenticatedAppAccessRequestsRoute,
  AuthenticatedAppAppointmentsRoute: AuthenticatedAppAppointmentsRoute,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppClinicalRoute: AuthenticatedAppClinicalRoute,
  AuthenticatedAppCommissionsRoute: AuthenticatedAppCommissionsRoute,
  AuthenticatedAppDealerLedgerRoute: AuthenticatedAppDealerLedgerRoute,
  AuthenticatedAppDealerPaymentsRoute: AuthenticatedAppDealerPaymentsRoute,
  AuthenticatedAppDealersRoute: AuthenticatedAppDealersRoute,
  AuthenticatedAppDeliveriesRoute: AuthenticatedAppDeliveriesRoute,
  AuthenticatedAppDistributionCatalogRoute:
    AuthenticatedAppDistributionCatalogRoute,
  AuthenticatedAppDistributionDashboardRoute:
    AuthenticatedAppDistributionDashboardRoute,
  AuthenticatedAppDistributionReportsRoute:
    AuthenticatedAppDistributionReportsRoute,
  AuthenticatedAppDoctorsRoute: AuthenticatedAppDoctorsRoute,
  AuthenticatedAppHospitalsRoute: AuthenticatedAppHospitalsRoute,
  AuthenticatedAppInventoryRoute: AuthenticatedAppInventoryRoute,
  AuthenticatedAppLabsRoute: AuthenticatedAppLabsRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRoute,
  AuthenticatedAppLifecycleRoute: AuthenticatedAppLifecycleRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppNutritionistsRoute: AuthenticatedAppNutritionistsRoute,
  AuthenticatedAppPatientsRoute: AuthenticatedAppPatientsRouteWithChildren,
  AuthenticatedAppPaymentsRoute: AuthenticatedAppPaymentsRoute,
  AuthenticatedAppPharmaciesRoute: AuthenticatedAppPharmaciesRoute,
  AuthenticatedAppPlansRoute: AuthenticatedAppPlansRoute,
  AuthenticatedAppPortalRoute: AuthenticatedAppPortalRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSalesOrdersRoute: AuthenticatedAppSalesOrdersRoute,
  AuthenticatedAppSensorsRoute: AuthenticatedAppSensorsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
  AuthenticatedAppTradeInvoicesRoute:
    AuthenticatedAppTradeInvoicesRouteWithChildren,
  AuthenticatedAppVehiclesRoute: AuthenticatedAppVehiclesRoute,
  AuthenticatedAppVisitAuditRoute: AuthenticatedAppVisitAuditRoute,
  AuthenticatedAppVisitFormSettingsRoute:
    AuthenticatedAppVisitFormSettingsRoute,
  AuthenticatedAppVisitsRoute: AuthenticatedAppVisitsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetPasswordRoute: SetPasswordRoute,
  ApiPublicHooksBackupSnapshotRoute: ApiPublicHooksBackupSnapshotRoute,
  ApiPublicHooksDealerDunningRoute: ApiPublicHooksDealerDunningRoute,
  ApiPublicHooksDealerStatementRoute: ApiPublicHooksDealerStatementRoute,
  ApiPublicHooksDispatchNotificationsRoute:
    ApiPublicHooksDispatchNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
